[package]
name = "plug_node"
version = "0.0.1"
authors = ["Zacaria <z@havesomeceode.io>"]
license = "MIT"

[lib]
name = "plug_node"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
#libc = "0.2"
neon = "0.1.22"
num_cpus = "1.4.0"

[profile.dev]
rpath = true
